In [1]:
import numpy as np

In [2]:
ori_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ori_array.shape

(12,)

In [7]:
ori_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
re_array = ori_array.reshape(-1 ,1)
re_array 

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [4]:
re_array.shape

(12, 1)

In [5]:
re_array = ori_array.reshape(3 ,4)

In [6]:
re_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
re_array.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])